feat: add endpoints, middleware, Prisma & MongoDB to users service
CS3219-AY2324S1/ay2324s1-course-assessment-g03 pull request #20
Opened 2023-10-09 18:52 UTC by sheimoria

# Changes
- [x] Add endpoints (`GET`, `POST`, `PUT`, `DELETE` users)
- [x] Add middleware (`cors`, `helmet`, `jwt`, `logger`, `swagger`)
- [x] Add Prisma ORM with `User` and `Question` schema
- [x] Initialise and connect to MongoDB Atlas with env var `DATABASE_URL`
- [x] Add env vars (`JWT_SECRET`, `DATABASE_URL`) to Pulumi config
- [x]  Add Prettier and ESLint config

TODO:
- [ ] Add JWT verification

2023-10-10 08:27 UTC, raynerljm requested changes
few changes requested as discussed

2023-10-10 08:27 UTC, raynerljm commented on backend/users-service/app/src/middlewares/users.middleware.ts
> +    .use(cors())
can specify the FE origin

2023-10-10 08:27 UTC, raynerljm commented on backend/users-service/app/src/middlewares/users.middleware.ts
> +        jwt({
as discussed can remove

2023-10-10 08:27 UTC, raynerljm commented on backend/users-service/app/src/controllers/users.controller.ts
> +export const post = ({ body }: { body: CreateUserBody }) => create(body)
can add a `TODO` to do role validation (need to discuss the implementation)

but idea is that a non-admin user should not be able to make themselves or others admin

2023-10-10 08:27 UTC, raynerljm commented on backend/users-service/infra/Pulumi.prod.yaml
> +  users-service-infra:jwtSecret:
as discussed can remove this

2023-10-10 08:27 UTC, raynerljm commented on backend/users-service/infra/Pulumi.prod.yaml
> +  users-service-infra:databaseUrl:
as discussed - up to u whether u want to pass connection string or init atlas MongoDB within pulumi

2023-10-10 08:27 UTC, raynerljm commented on backend/users-service/infra/Pulumi.staging.yaml
> +  users-service-infra:jwtSecret:
as discussed can remove this

2023-10-10 08:27 UTC, raynerljm commented on backend/users-service/.prettierrc.json
> +{
as discussed can standardize the prettier w the one in the fe

2023-10-10 08:27 UTC, raynerljm commented on backend/users-service/infra/index.ts
> +const jwtSecret = config.requireSecret('jwtSecret')
as discussed can remove

2023-10-10 15:50 UTC, sheimoria commented on backend/users-service/app/src/middlewares/users.middleware.ts
> +        jwt({
Resolved in 5139e3bb0fe3d0d3edf4e402504878d4b588f9f6

2023-10-10 15:51 UTC, sheimoria commented on backend/users-service/infra/Pulumi.prod.yaml
> +  users-service-infra:jwtSecret:
Resolved in 5139e3bb0fe3d0d3edf4e402504878d4b588f9f6

2023-10-10 15:51 UTC, sheimoria commented on backend/users-service/infra/Pulumi.staging.yaml
> +  users-service-infra:jwtSecret:
Resolved in 5139e3bb0fe3d0d3edf4e402504878d4b588f9f6

2023-10-10 15:51 UTC, sheimoria commented on backend/users-service/infra/index.ts
> +const jwtSecret = config.requireSecret('jwtSecret')
Resolved in 5139e3bb0fe3d0d3edf4e402504878d4b588f9f6

2023-10-10 15:52 UTC, sheimoria commented on backend/users-service/app/src/middlewares/users.middleware.ts
> +    .use(cors())
Resolved in 5139e3bb0fe3d0d3edf4e402504878d4b588f9f6

2023-10-10 15:56 UTC, sheimoria commented on backend/users-service/app/src/controllers/users.controller.ts
> +export const post = ({ body }: { body: CreateUserBody }) => create(body)
Resolved in 85385a3e713193a3f528369b85496ea88edc2ff9

2023-10-10 16:11 UTC, sheimoria commented on backend/users-service/.prettierrc.json
> +{
Resolved in d8c4ab7ca0323cf0dc91eba8a543f8af56febf72

2023-10-11 04:54 UTC, raynerljm approved these changes
lgtm! 🎉

2023-10-11 05:04 UTC, merged